mondoohq/mondoo-operator

api/v1alpha1/mondooauditconfig_types.go
config/manager/kustomization.yaml
config/samples/k8s_v1alpha1_mondooauditconfig.yaml
controllers/mondooauditconfig_controller.go
controllers/nodes.go
controllers/workloads.go

Closes #50 
Moves logic into submethods and introduces a simple interface to call entrypoint reconcile method on objects.

🧹refactor controller

---

.github/workflows/docker-publish.yaml

fix: add golang env

---

.github/workflows/docker-publish.yaml

Adding in operator-sdk at make-bundle step + env var manipulation

---

.github/workflows/helm-release.yaml

Changed folder where charts are searched for

changed charts folder

---

.github/workflows/helm-release.yaml
charts/mondoo-operator/.helmignore
charts/mondoo-operator/Chart.yaml
charts/mondoo-operator/templates/_helpers.tpl
charts/mondoo-operator/templates/deployment.yaml
charts/mondoo-operator/templates/leader-election-rbac.yaml
charts/mondoo-operator/templates/manager-config.yaml
charts/mondoo-operator/templates/manager-rbac.yaml
charts/mondoo-operator/templates/metrics-reader-rbac.yaml
charts/mondoo-operator/templates/metrics-service.yaml
charts/mondoo-operator/templates/mondooauditconfig-crd.yaml
charts/mondoo-operator/templates/proxy-rbac.yaml
charts/mondoo-operator/templates/workload-rbac.yaml
charts/mondoo-operator/values.yaml

Switching to standard repository structure to release helm chart

switching to standard helm chart release process

---

Makefile
README.md
docs/deployment-configurations.md
docs/development.md
docs/user-manual-helm.md
docs/user-manual-kubectl.md
docs/user-manual-olm.md

- apply markdown formatting with prettier
- add README.md
- re-add helm documentation

🧹 update docs

---

.github/workflows/helm-release.yaml
charts/mondoo-operator/Chart.yaml
charts/mondoo-operator/values.yaml

https://github.com/helm/chart-releaser-action/pull/96 
Currently helm chart release action does not work on tags. There is an open PR addressing this issue. For now , I have switched trigger to pushes on main

Helm rel fix

---

docs/development.md
docs/user-manual-helm.md
docs/user-manual-kubectl.md
docs/user-manual-olm.md

This change simplifies the setup instructions around the Mondoo secret

🧹 update docs and simplify instructions around mondoo secret setup

---

.github/workflows/generate-manifests.yaml

using IMG flag to point generated manifests to semver tag

---

.github/workflows/docker-publish.yaml

fixing tags reference in container image build

---

charts/mondoo-operator/Chart.yaml
charts/mondoo-operator/values.yaml

 🧹bump chart version

---

.github/workflows/helm-release.yaml
charts/mondoo-operator/Chart.yaml

Updated Version for Change in description

🧹 update helm chart description

---

docs/user-manual-helm.md
docs/user-manual-olm.md

🧹 remove minikube references from helm docs

---

.github/workflows/e2e-olm.yaml

🐛 fix typo in tag reference for olm e2e test

---

docs/user-manual-kubectl.md
docs/user-manual-olm.md

🧹  minor docs fix

---

README.md

🧹 add tested kubernetes distributions to readme

---

README.md

- adds more context about the project
- add architectural picture

🧹 update project readme

---

.github/workflows/docker-publish.yaml
.github/workflows/e2e.yaml
.github/workflows/helm-release.yaml
config/default/kustomization.yaml
config/manager/kustomization.yaml
config/samples/k8s_v1alpha1_mondooauditconfig.yaml
config/webhook/kustomization.yaml
controllers/webhook-manifests.yaml
controllers/webhooks_test.go
docs/deployment-configurations.md
docs/development.md
docs/user-manual-helm.md
docs/user-manual-kubectl.md
docs/user-manual-olm.md
test/deployment-policy.yaml

🧹 simplify default namespace

---

config/manifests/bases/mondoo-operator.clusterserviceversion.yaml
config/manifests/kustomization.yaml
config/manifests/patches/description.yaml

🧹 use proper description in olm manifest for operator hub

---

docs/user-manual-olm.md

- updates olm installation instructions
- add FAQ for cases where the dev environment has not enough memory for scheduling

🧹 update install docs for olm

---

.github/workflows/e2e-olm.yaml

🐛 remove if condition for e2e olm test

---

.github/workflows/publish.yaml

🐛 add if conditions for tasks that run for released tags

---

controllers/mondooauditconfig_controller.go

⭐️ requeue reconcile on weekly basis

---

.github/workflows/e2e-olm.yaml
.github/workflows/publish.yaml

uses inputs for olm e2e test to allow manual trigger

🐛 use input for e2e olm test to allow manual trigger

---

README.md
config/manifests/patches/description.yaml
docs/user-manual-helm.md
docs/user-manual-kubectl.md
docs/user-manual-olm.md

- update instructions for manual bundle installation
- update instructions for operatorhub

⭐️ update olm install descriptions

---

.github/workflows/publish.yaml

uses the approach recommended by GitHub staff https://github.community/t/how-to-pass-environment-variable-to-an-input/16277/7

🐛 fix issue where inputs have no access to env variables

---

.actrc
.github/workflows/e2e-olm.yaml
.github/workflows/e2e.yaml
.github/workflows/publish.yaml
.github/workflows/release-helm-chart.yaml
.github/workflows/release-manifests.yaml
.github/workflows/unit.yaml
.github/workflows/validate-actions.yaml
Makefile

- uses act for GitHub action validation
- do not use env for input variables since this is not working as expected
- update GitHub workflow job names

🐛 reverse env variable handling and add github actions validation

---

.github/workflows/publish.yaml

🐛 remove runs-on for jobs that call another workflow

---

.github/workflows/release-helm-chart.yaml

used `luisico/chart-releaser-action@on-tags` action until https://github.com/helm/chart-releaser-action/issues/60 is open

🐛 use helm chart releaser action for tags

---

README.md

Add the license text and badge to make it clear. Also cleanup markdown
lint and issues flagged in grammarly.
Signed-off-by: Tim Smith <tim@mondoo.com>

Readme cleanup + add license

---

controllers/nodes.go
controllers/nodes_test.go
controllers/suite_test.go
controllers/workloads_test.go
go.mod
go.sum

⭐️ unit-testing for nodes and workload configuration

---

api/v1alpha1/mondooauditconfig_types.go
config/crd/bases/k8s.mondoo.com_mondooauditconfigs.yaml
config/samples/k8s_v1alpha1_mondooauditconfig.yaml

This has been moved into a condition under MondooOperatorConfig.

🐛 cleaup leftover status field in MondooAuditConfig

---

.github/workflows/e2e-olm.yaml
.github/workflows/e2e.yaml
.github/workflows/release-helm-chart.yaml

- stores creds from GITHUB secret before we upload them to Kubernetes
- deletes creds after they have been uploaded to Kubernetes

🐛 store creds before we upload the creds to kubernetes

---

release.sh

re-open https://github.com/mondoohq/mondoo-operator/pull/221 since Github had issues with GitHub Actions

🧹 tweak release.sh script

---

.github/workflows/e2e-olm.yaml
.github/workflows/e2e.yaml

Fix credential parsing. Using base64 works

:bug: fix credentials parsing

---

.github/workflows/e2e.yaml
.github/workflows/unit.yaml

🧹 remove e2e and unit from docs path

---

.github/actions/spelling/expect.txt
RELEASE.md
docs/user-manual-kubectl.md

Signed-off-by: Patrick Münch <patrick.muench1111@gmail.com>

add a short desc for the creds.json

---

.github/workflows/e2e.yaml
.github/workflows/release-helm-chart.yaml
config/samples/k8s_v1alpha1_mondooauditconfig.yaml
controllers/nodes.go
controllers/workloads.go

⭐️ Readiness Probe

---

api/v1alpha1/mondoooperatorconfig_types.go
config/crd/bases/k8s.mondoo.com_mondoooperatorconfigs.yaml
controllers/mondooauditconfig_controller.go
controllers/nodes.go
controllers/utils.go
controllers/webhooks.go
controllers/webhooks_test.go
controllers/workloads.go

fixes #197,#198 
Skip Mondoo container image resolution when flag is used

⭐️ Skip resolving mondoo image

---

Makefile
config/default/manager_auth_proxy_patch.yaml
config/manager/manager.yaml
docs/user-manual-olm.md
go.mod
go.sum

⭐ Support operator-sdk 1.18

---

.github/workflows/publish.yaml
Makefile
bundle.Dockerfile
docs/development.md

⭐ Upgrade to operator-sdk 1.19.0

---

config/rbac/role.yaml
config/rbac/role_nodes.yaml
controllers/mondooauditconfig_controller.go

🐛 Fixed RBAC definitions

---

controllers/mondooauditconfig_controller.go

I forgot to add this comment for the RBAC. It's good to have it so we don't change it again later 

🧹 Added comment to explain RBAC configuration

---

controllers/mondooauditconfig_controller.go

🧹 Re-use finalizer functions from controller-runtime

---

.github/workflows/lint.yaml

🧹 Increase lint timeout

---

.github/workflows/e2e-olm.yaml
.github/workflows/release-helm-chart.yaml
.github/workflows/tests.yaml

Try to gather some status on the state of the Pods if OLM and/or Helm release validation fails.

🧹 save helm/olm logs on failure

---

charts/mondoo-operator/Chart.yaml
charts/mondoo-operator/templates/deployment.yaml
charts/mondoo-operator/templates/manager-rbac.yaml
charts/mondoo-operator/values.yaml
config/manager/kustomization.yaml

mondoo-operator v0.2.4

---

.github/workflows/release-helm-chart.yaml

s/upload-artifacts/upload-artifact/

🐛 fix spelling of github action

---

controllers/scanapi/deploy.go
controllers/webhooks/webhooks.go
controllers/webhooks/webhooks_test.go
pkg/utils/k8s/equality.go
pkg/utils/k8s/equality_test.go
pkg/utils/k8s/update.go
pkg/utils/k8s/update_test.go
tests/framework/utils/container_image.go

🧹 Extend unit tests for webhooks and utils packages

---

charts/mondoo-operator/Chart.yaml
charts/mondoo-operator/values.yaml
config/manager/kustomization.yaml

mondoo-operator v0.2.5

---

.github/workflows/publish.yaml

sign the actual bundle image

---

.github/workflows/release-helm-chart.yaml
config/samples/k8s_v1alpha2_mondooauditconfig.yaml
config/samples/k8s_v1alpha2_mondooauditconfig_minimal.yaml

🐛  Fixed helm chart tests

---

config/rbac/k8s_resources_scanning_clusterrolebinding.yaml

🐛 Fixed ClusterRoleBinding for k8s resource scanning

---

docs/user-manual.md

🧹  Add mondooCredsSecretRef to MondooAuditConfig in user manual

---

.github/workflows/e2e-olm.yaml
.github/workflows/release-helm-chart.yaml
tests/framework/installer/installer.go
tests/integration/audit_config_base_suite.go

🐛 Fix helm and olm release workflows

---

.github/workflows/publish.yaml
Makefile
bundle.Dockerfile
charts/mondoo-operator/Chart.yaml
charts/mondoo-operator/values.yaml
config/manager/kustomization.yaml

mondoo-operator v0.2.9

---

charts/mondoo-operator/Chart.yaml
charts/mondoo-operator/templates/mondooauditconfig-crd.yaml
charts/mondoo-operator/values.yaml
config/manager/kustomization.yaml

mondoo-operator v0.2.10

---

config/rbac/role.yaml
controllers/mondooauditconfig_controller.go
controllers/nodes/deployment_handler.go
controllers/nodes/resources.go
controllers/nodes/resources_test.go

🐛 Refactor CronJobName to not return names longer than 52 chars

---

charts/mondoo-operator/Chart.yaml
charts/mondoo-operator/templates/manager-rbac.yaml
charts/mondoo-operator/values.yaml
config/manager/kustomization.yaml

operator v0.2.11

---

controllers/nodes/deployment_handler.go
controllers/nodes/deployment_handler_test.go
controllers/nodes/inventory.yaml
controllers/nodes/resources.go
controllers/nodes/resources_test.go

🐛 Fix node scanning jobs for GKE nodes

---

pkg/mondooclient/client.go

Make sure we try to reach out to /Scan/RunKubernetesManifest

🐛 the endpoint does not end with an 's'

---

charts/mondoo-operator/Chart.yaml
charts/mondoo-operator/templates/deployment.yaml
charts/mondoo-operator/values.yaml
config/manager/kustomization.yaml

mondoo 0.2.13

---

docs/user-manual.md

Signed-off-by: Letha Dunn <letha@mondoo.com>
Co-authored-by: Joel Diaz <joel@mondoo.com>
Co-authored-by: Tim Smith <tim@mondoo.com>

🧹 Documentation cleanup

---

charts/mondoo-operator/Chart.yaml
charts/mondoo-operator/values.yaml
config/manager/kustomization.yaml

mondoo-operator v0.2.15

---

controllers/workloads.go

Remove the last remaining places where the Reconcile() loop would exit early in non-error cases.
Additionally, rework how the workload codepath determines when an update to the Pods is needed (for example if the contents of the ConfigMap change). Instead of indicating that a change was made to the ConfigMap and then putting a timestamp on the Deployment to force a re-deploy, just compute the hash of the ConfigMap contents and include that in the Deployment as an annoation. Now if the ConfigMap contents change, the hash will change, and the workload scanning Pod will be re-deployed even if an error is encountered between updating the ConfigMap and updating the Deployment.

🧹 no more early exits during Reconcile()

---

controllers/admission/deployment_handler.go
controllers/nodes/deployment_handler.go
controllers/workloads.go

mark some of the cleanup functions that we can remove with 0.4.0

---

.github/actions/spelling/expect.txt
RELEASE.md
docs/operator-upgrades.md

⭐ Document versioning and upgrade strategy

---

.github/workflows/publish.yaml

Referencing a step across Jobs didn't work.

Use Job step to get version

---

.github/workflows/lint.yaml
Makefile
controllers/admission/deployment_handler.go
controllers/k8s_scan/deployment_handler_test.go
controllers/mondooauditconfig_controller.go
controllers/nodes/deployment_handler_test.go
tests/framework/installer/installer.go
tests/framework/utils/k8s_helper.go
tests/framework/utils/manifest_utils.go

🧹 Fix typos and staticchecks

---

bundle.Dockerfile
charts/mondoo-operator/Chart.yaml
charts/mondoo-operator/values.yaml
config/manager/kustomization.yaml
config/webhook/kustomization.yaml

Release 0.4.3

---

pkg/utils/mondoo/container_image_resolver.go

🧹 Pin mondoo/client version to 6

---

controllers/nodes/resources.go
tests/framework/utils/k8s_helper.go

🐛 Make sure we do not endlessly update node scanning cronjobs

---

controllers/admission/conditions.go
controllers/integration/integration_controller.go
controllers/k8s_scan/conditions.go
controllers/k8s_scan/container_image/conditions.go
controllers/k8s_scan/container_image/deployment_handler_test.go
controllers/k8s_scan/deployment_handler_test.go
controllers/nodes/conditions.go
controllers/nodes/deployment_handler_test.go
controllers/scanapi/conditions.go
pkg/utils/mondoo/condition.go

🧹 Always set conditions in MondooAuditConfig status

---

.github/workflows/publish.yaml
.github/workflows/tests.yaml
Makefile
controllers/admission/webhook-manifests.yaml
tests/framework/installer/installer.go
tests/framework/installer/settings.go
tests/framework/utils/k8s_helper.go
tests/integration/audit_config_base_suite.go
tests/integration/audit_config_upgrade_test.go

This test will install the latest release and then update with
the manifest present in the branch.
Fixes #322

🧹 Add integration test for operator update

---

tests/integration/audit_config_base_suite.go

🧹Enabled MondooAuditConfig status checking in upgrade test

---

controllers/integration/integration_controller.go
controllers/mondooauditconfig_controller.go
controllers/status/operator_status.go
pkg/utils/mondoo/integration.go

🐛 Fix panics on initial integration check-in

---

cmd/mondoo-operator/k8s_scan/cmd.go

🐛  Make sure k8s scan exits on request error

---

controllers/scanapi/resources.go

🧹 Add liveness probe for Scan API

---

.github/actions/spelling/expect.txt
.github/workflows/publish.yaml
.github/workflows/spell-check.yaml
.github/workflows/tests.yaml

🧹 Use latest k8s versions for integration tests

---

tests/framework/installer/installer.go
tests/integration/audit_config_base_suite.go

🧹 Cleanup label change

---

controllers/admission/deployment_handler.go
controllers/nodes/deployment_handler.go
controllers/nodes/deployment_handler_test.go
controllers/nodes/resources.go
controllers/nodes/resources_test.go
pkg/utils/k8s/namespace.go

🐛 follow the platformid pattern

---

.github/workflows/edge-integration-tests.yaml
.github/workflows/integration-tests.yaml
.github/workflows/test-report.yaml
.github/workflows/tests.yaml

Fix setting the secrets for the integration tests and print the inputs so we can more easily debug if needed

🐛 Fix edge integration workflow

---

README.md
docs/operator-upgrades.md

🧹 Update upgrade docs in prep for 1.0 behavior

---

.github/workflows/integration-tests.yaml
cmd/mondoo-operator/k8s_scan/cmd.go
tests/framework/installer/installer.go
tests/framework/utils/k8s_helper.go

🧹 Print full response on k8s scan error

---

tests/integration/audit_config_base_suite.go

🧹 Improve integration tests stability

---

pkg/feature_flags/feature_flags.go
pkg/mondooclient/client.go

⭐ Add feature flag for workload discovery

---

.github/workflows/publish.yaml
.github/workflows/tests.yaml

Updated the go mod and build caching according to the official docs (see [here](https://github.com/actions/cache/blob/main/examples.md#go---modules))

🧹 Update go mod and build caching

---

.github/env
.github/workflows/lint.yaml
.github/workflows/publish.yaml
Makefile
api/v1alpha2/groupversion_info.go
cmd/mondoo-operator/k8s_scan/cmd.go
cmd/mondoo-operator/webhook/cmd.go
controllers/service_monitor.go
go.mod
pkg/mondooclient/client.go
pkg/mondooclient/client_test.go
pkg/utils/k8s/namespace.go
pkg/webhooks/handler/webhook_test.go
tests/framework/utils/executor.go
tests/framework/utils/manifest_utils.go

Since we are upgrading the Mondoo client to Go 1.19 it would be good to have the operator upgraded as well

⭐ Upgrade to Go 1.19

---

charts/mondoo-operator/Chart.yaml
charts/mondoo-operator/values.yaml
config/manager/kustomization.yaml
config/webhook/kustomization.yaml

mondoo-operator 1.1.0

---

pkg/mondooclient/client.go

🐛 Fixed workload discovery feature flag

---

.github/terraform/aws/README.md
docs/user-manual.md

🧹 update path to terraform files

---

.github/workflows/integration-tests.yaml
controllers/nodes/resources.go

🐛 Fix rpm package discovery

---

charts/mondoo-operator/Chart.yaml
charts/mondoo-operator/values.yaml
config/manager/kustomization.yaml
config/webhook/kustomization.yaml

mondoo-operator 1.2.1

---

.github/workflows/spell-check.yaml

Ignore company names in spellcheck

---

go.mod
go.sum

go get -u github.com/go-logr/logr
go mod tidy

🧹 update go-logr/logr

---

.github/workflows/integration-tests.yaml
.github/workflows/lint.yaml
.github/workflows/publish.yaml
.github/workflows/release-manifests.yaml
.github/workflows/tests.yaml
.github/workflows/validate-actions.yaml

🧹 Update actions/checkout to v3

---

.github/workflows/cloud-tests.yaml

Tests reporting was not working correctly. This should be the final tweak to the cloud tests (hopefully)

🐛 Fix test results reporting for cloud tests

---

.github/terraform/aws/outputs.tf
.github/workflows/publish.yaml
.github/workflows/tests.yaml

🧹 Scan our artifacts with Mondoo

---

.github/workflows/lint.yaml
.golangci.yml
Makefile

🧹 Update golangci-lint

---

.vscode/settings.json

This makes the VS Code settings consistent with the rest of our repos

🧹 Add tab settings to vscode configuration

---

.github/actions/spelling/allow.txt
.github/actions/spelling/expect.txt
.github/workflows/spell-check.yaml

Get stuff into the upstream dictionary instead

Remove some word exceptions in cspell now

---

.github/workflows/cleanup-mondoo-space.yaml
.github/workflows/integration-tests.yaml
scripts/cleanup_operator_assets.sh
scripts/cleanup_operator_space_cicd.sh

🧹 Cleanup Mondoo space after integration tests

---

README.md

We forgot to update those when we implemented the cloud integration tests

🧹 Update tested k8s versions in readme

---

cmd/mondoo-operator/operator/cmd.go

During the startup, the scan API secrets are not yet created.
Fixes #572

🐛 Fix operator startup

---

.github/workflows/edge-integration-tests.yaml
.github/workflows/integration-tests.yaml

This should help us see failed workflows such as the edge integration tests or cloud tests earlier

🧹 Add discord notifications for failed workflows

---

.github/workflows/cloud-tests.yaml

🧹 Add schedule for cloud tests

---

.github/workflows/tests.yaml
.github/workflows/validate-actions.yaml

terraform is now terraform-hcl

Update the GitHub Actions config for new Mondoo action

---

charts/mondoo-operator/Chart.yaml
charts/mondoo-operator/values.yaml
config/manager/kustomization.yaml
config/webhook/kustomization.yaml

mondo 1.6.2

---

controllers/mondooauditconfig_controller.go
controllers/mondooauditconfig_controller_test.go
go.mod
go.sum

This should prevent any race-conditions, which were previously possible.
Fixes #433

🐛 Fix `MondooAuditConfig` Status Reconcile

---

charts/mondoo-operator/Chart.yaml
charts/mondoo-operator/values.yaml
config/manager/kustomization.yaml
config/webhook/kustomization.yaml

mondoo-operator 1.6.3

---

.github/workflows/cloud-tests.yaml

🧹 Update terraform action

---

.github/workflows/cloud-tests.yaml
.github/workflows/publish.yaml
tests/framework/utils/k8s_helper.go

🧹 Log MondooAuditConfig for failed integration tests

---

charts/mondoo-operator/Chart.yaml
charts/mondoo-operator/templates/deployment.yaml
charts/mondoo-operator/values.yaml
config/manager/kustomization.yaml
config/webhook/kustomization.yaml

mondoo-operator 1.6.4

---

README.md

Updates README with link to GitHub community.
Signed-off-by: Scott Ford <scott@scottford.io>

Adds link to GitHub Discussions community

---

.github/workflows/edge-integration-tests.yaml
.github/workflows/integration-tests.yaml

🧹 Use edge config for edge tests

---

charts/mondoo-operator/Chart.yaml
charts/mondoo-operator/templates/deployment.yaml
charts/mondoo-operator/templates/mondooauditconfig-crd.yaml
charts/mondoo-operator/values.yaml
release.sh

mondoo 1.6.5

---

config/manager/kustomization.yaml
config/webhook/kustomization.yaml

missed changes to config/* for the 1.6.5 version

---

.github/workflows/integration-tests.yaml

This is according to this comment: https://github.com/actions/runner/issues/1483\#issuecomment-1042393939

🐛 Fix boolean for useEdge

---

config/manager/manager.yaml

annotate the mondoo-operator namespace

---

pkg/utils/mondoo/container_image_resolver.go

move to v7 mondoo client for scans

---

charts/mondoo-operator/Chart.yaml
charts/mondoo-operator/values.yaml
config/manager/kustomization.yaml
config/webhook/kustomization.yaml

mondoo 1.6.6

---

pkg/mondooclient/client.go

🐛 Discover k8s cluster asset

---

.github/workflows/publish.yaml

🐛 Ensure manifest gets latest tag

---

charts/mondoo-operator/Chart.yaml
charts/mondoo-operator/values.yaml
config/manager/kustomization.yaml
config/webhook/kustomization.yaml

mondoo 1.6.8

---

.vscode/launch.json
pkg/mondooclient/client.go

🐛 Cleanup Scan API endpoint

---

docs/user-manual.md

📄 Install mondoo client into multiple namespaces

---

.github/workflows/tests-forks.yaml

🧹 Add debugging and read permissions to fork-PRs workflow

---

.github/workflows/tests-forks.yaml

🐛 Fix debug output

---

.github/workflows/tests-forks.yaml

🧹 Replace labeler action with gh cli

---

.github/env
Makefile

🧹 Bump operator-sdk to 1.25.0

---

bundle.Dockerfile
charts/mondoo-operator/Chart.yaml
charts/mondoo-operator/values.yaml
config/manager/kustomization.yaml
config/webhook/kustomization.yaml

mondoo-operator 1.7.1

---

.github/workflows/publish.yaml

🐛 Bump cosign

---

.github/workflows/publish.yaml

🐛 Bump cosign for bundles

---

.github/workflows/publish.yaml

🐛 Bump opm version

---

.github/workflows/cleanup-mondoo-space.yaml

Edge integration tests report to Mondoo edge. So we need to cleanup there also.
Fixes #659

🧹 Regularly clean up edge assets and projects

---

.github/workflows/cleanup-mondoo-space.yaml

🧹 Update actions to use Node 16

---

charts/mondoo-operator/Chart.yaml
charts/mondoo-operator/values.yaml
config/manager/kustomization.yaml
config/webhook/kustomization.yaml

mondoo-operator 1.8.0

---

controllers/mondooauditconfig_controller_test.go
controllers/status/operator_status.go
controllers/status/operator_status_test.go
controllers/status/status_reporter_test.go

Fixes #674 
Will report cnspec version once we migrate to cnspec

🧹 Set operator version in last state status object

---

.github/workflows/tests-forks.yaml

Fixes https://github.com/mondoohq/mondoo-operator/actions/runs/3443580018/jobs/5745262872

🐛 Fix remove label

---

charts/mondoo-operator/Chart.yaml
charts/mondoo-operator/values.yaml
config/manager/kustomization.yaml
config/webhook/kustomization.yaml

mondoo-operator-1.8.1

---

.github/workflows/cloud-tests.yaml

🐛 Supply defaults when running on schedule

---

pkg/webhooks/handler/webhook.go

GKE, AKS, ... regularly (every 30s-60s) apply their addons. This creates update events which are send to the webhook, which creates CI/CD assets in the backend. But these updates do not contain real changes, only the `resourceVersion` changed. So, we skip them.
This is a known bug in older k8s versions: https://github.com/kubernetes/kubernetes/issues/95460
Fixes #685

🐛 Skip server-side applies without real change

---

.github/workflows/cleanup-mondoo-space.yaml
.github/workflows/publish.yaml
.github/workflows/security-tests.yaml

🧹 Use new action with cnspec image

---

cmd/mondoo-operator/garbage_collect/cmd.go
pkg/garbagecollection/garbagecollection.go

🧹 Use fixed GC API field

---

.github/dependabot.yml

🧹 Add github-actions to dependabot

---

bundle.Dockerfile
charts/mondoo-operator/Chart.yaml
charts/mondoo-operator/values.yaml
config/manager/kustomization.yaml
config/webhook/kustomization.yaml

mondoo-operator-1.9.0

---

tests/integration/audit_config_base_suite.go

https://github.com/mondoohq/mondoo-operator/actions/runs/3564184472

🐛 Fix cloud tests

---

charts/mondoo-operator/Chart.yaml
charts/mondoo-operator/values.yaml
config/manager/kustomization.yaml
config/webhook/kustomization.yaml

mondoo-operator-1.9.1

---

.github/terraform/aws/README.md

Align this with all our other repos

Update how we type our Mondoo, Inc.

---

.github/actions/spelling/line_forbidden.patterns
.github/workflows/spell-check.yaml

Use the latest in both actions and use all our patterns

Update our spellcheck config + versions

---

tests/integration/audit_config_base_suite.go

🧹 Make sure port-forward is really restarted

---

.github/workflows/cloud-tests.yaml

🐛 Add protoc to cloud tests

---

config/manager/manager.yaml
controllers/admission/resources.go
controllers/k8s_scan/container_image/resources.go
controllers/k8s_scan/resources.go
controllers/nodes/resources.go
controllers/scanapi/resources.go

🧹 Explicitly set privileged to false

---

.github/workflows/publish.yaml

Added a step to install protoc before building the binaries for the operator

🐛 Fix container build workflow

---

.github/workflows/cloud-tests.yaml

🐛 Set service account env var for cloud tests

---

.github/workflows/publish.yaml

🐛 Fix publish tests

---

Makefile

🐛 Prevent GitHub API rate limit on kustomize install

---

charts/mondoo-operator/Chart.yaml
charts/mondoo-operator/values.yaml
config/manager/kustomization.yaml
config/webhook/kustomization.yaml

mondoo-operator-1.11.0

---

.github/workflows/publish.yaml

🧹 Fix helm action warning

---

charts/mondoo-operator/Chart.yaml
charts/mondoo-operator/values.yaml
config/manager/kustomization.yaml
config/webhook/kustomization.yaml

mondoo-operator-1.11.1

---

controllers/nodes/resources.go
controllers/scanapi/resources.go
pkg/feature_flags/feature_flags.go
pkg/utils/mondoo/container_image_resolver.go
pkg/utils/mondoo/container_image_resolver_test.go
pkg/utils/mondoo/fake/container_image_resolver.go
tests/framework/utils/audit_config.go

Use cnspec by default and remove mondoo client dependencies

🧹 Remove dependency to mondoo client

---

cmd/mondoo-operator/garbage_collect/cmd.go
cmd/mondoo-operator/k8s_scan/cmd.go

Container image assets are stored as "docker-image"
Make sure we use the right string when trying to garbage collect old
ones.

🐛  container image gc

---

Makefile
charts/mondoo-operator/Chart.yaml
charts/mondoo-operator/templates/deployment.yaml
charts/mondoo-operator/values.yaml
config/manager/kustomization.yaml
config/webhook/kustomization.yaml

pin to helmify 0.3.23 to avoid the issue we're trying to fix in https://github.com/arttor/helmify/pull/89
and pick an old enough version to avoid the quoting of environment variables too

operator v1.12.2

---

scripts/push-virtual-tag.sh

Forgot to update the script as well in #772

🐛 fix cosign command in virtual tags script

---

charts/mondoo-operator/templates/deployment.yaml
cmd/mondoo-operator/k8s_scan/cmd.go
config/manager/manager.yaml
pkg/feature_flags/feature_flags.go

We have had garbage collection enabled for a while by default. The feature flag for it can go away now

🧹 remove garbage collection feature flag

---

pkg/utils/k8s/delete_test.go

I noticed we never run those properly. I fixed it now

🧹 fix delete tests

---

docs/operator-upgrades.md
docs/user-manual.md

This should clarify some situations.
Fixes: https://github.com/mondoohq/server/issues/6272
Related-to: https://github.com/mondoohq/server/issues/6267

🐛 Extend Helm related docs

---

README.md

Remove the license badge in the readme

---

.github/workflows/test-report.yaml

Reverts mondoohq/mondoo-operator#942

Revert "🧹 Debug report test"

---

config/rbac/role.yaml
controllers/container_image/deployment_handler.go
controllers/k8s_scan/deployment_handler.go
controllers/mondooauditconfig_controller.go
controllers/nodes/deployment_handler.go
controllers/nodes/resources.go
pkg/utils/k8s/equality.go
pkg/utils/k8s/equality_test.go
tests/integration/audit_config_oom_test.go
tests/integration/audit_config_test.go

Seems like only node scanning has that issue
Fixes #991

🐛 fix concurrency policy for node scanning cronjobs

---

.copywrite.hcl
.github/env
Makefile
PROJECT
api/v1alpha2/mondooauditconfig_types.go
bundle.Dockerfile
cmd/mondoo-operator/operator/operator_status.go
config/default/manager_auth_proxy_patch.yaml
controllers/status/operator_status.go
controllers/status/operator_status_test.go
tests/integration/audit_config_base_suite.go

Upgrade the operator-sdk to 1.33.0. This can be tested by running the `release.sh` script locally with a sample version

🧹 update operator-sdk

---

config/manager/manager.yaml
controllers/container_image/resources.go
controllers/nodes/resources.go
pkg/client/scanapiclient/client.go
pkg/feature_flags/feature_flags.go
pkg/utils/mondoo/container_image_resolver.go

remove the old v9 feature flag and add a feature flag for v10

✨ add feature flag for using cnspec v10

---

.github/env
.github/workflows/cloud-tests.yaml
.github/workflows/integration-tests.yaml
.github/workflows/publish.yaml
Makefile
go.mod

- use prod for running the integration tests
- switch to go 1.22

🧹 use prod for integration testing

---

cmd/mondoo-operator/webhook/cmd.go
controllers/admission/resources.go
pkg/client/scanapiclient/client.go
pkg/client/scanapiclient/fakeserver/fakeserver.go
pkg/webhooks/handler/webhook.go

makes sure we actually verify we can talk to the scan api before marking the webhook as ready

✨ add real healtchecks for the admission controller

---

.github/dependabot.yml

i took that approach from cnquery. Hope it works here too

🧹 group dependabot updates

---

tests/framework/utils/k8s_helper.go
tests/integration/audit_config_base_suite.go
tests/integration/audit_config_oom_test.go

attempt to re-write the assertions for the admission e2e tests such that they become more robust

🧹 rewrite assertions for admission e2e tests

---

.github/workflows/tests.yaml

Execute the tests every Wednesday on a schedule

🧹 execute tests on cron schedule

---

.github/workflows/publish.yaml

these are causing some race condition in the backend and we cannot finish the release. At this point, they are not helping at all but just getting in the way

🧹 disable helm tests

---

controllers/mondoooperatorconfig_controller.go

If a HTTP proxy is specified, make sure the container resolution traffic is routed through it too

🐛 route container resolving via http proxy

---

pkg/utils/k8s/resources_requirements.go

We have seen some issues with the current default resource requirements so we increase them

🧹 increase default resource requirements

---

pkg/utils/mondoo/container_image_resolver.go

NOTE: the tests will fail until v11 is released

⭐️ cnspec v11

---

.copywrite.hcl
.github/actions/spelling/line_forbidden.patterns
.github/actions/spelling/reject.txt
LICENSE

Update spelling config + copyright year

---

cmd/mondoo-operator/operator/cmd.go

Applying the changes recommended here https://github.com/operator-framework/operator-sdk/issues/1813

🧹 increase leader elect timeouts

---

.github/env
go.mod
go.sum
tests/framework/nexus/assets/assets.go
tests/framework/nexus/k8s/integration.go
tests/framework/utils/k8s_helper.go

We removed a GQL API that was used in the integration tests logic. I modified the code to use the new APIs instead.
We also now discover k8s namespaces be default. I adjusted the tests to account for that

🧹 fix integration tests
