mondoohq/mondoo-operator

.gitignore, Dockerfile, Makefile
Add new makefile target 'buildah-build' to allow using 'buildah' for
building the container image locally.
As part of that work, buildah gets confused and starts asking questions
about where to fetch the golang:1.17 build container image from. Clarify
that by using a fully qualified name/path for the image
s|golang:1.17|docker.io/library/golang:1.17|
Lastly, add '.vscode' to the .gitignore file for the VSCode users of the
world.
=> ⭐️ updates to allow building with buildah

controllers/mondooauditconfig_controller.go, controllers/nodes.go, controllers/workloads.go
=> fixes for setting ControllerRef, error/requeue handing, and Status() updates

.github/workflows/e2e.yaml, .github/workflows/helm-release.yaml
Moved helm chart test from e2e to helm release. As we are releasing helm chart after a new operator release, it makes sense to test the released image using the chart.
=> 🧹 refactor helm release process

.github/workflows/e2e.yaml
'make undeploy' will delete the mondoo-operator Deployment/Pod.
This means the operator will never get a chance to clean up the
finalizer. This means 'make undeploy' hangs waiting for the
namespace to be deleted. And the namespace can't be cleaned up
because the MondooAuditConfig resource is waiting for the finalizer
to be removed.
Add an explicit step to delete the MondooAuditConfig to give the
operator a chance to remove the finalizer, and keep things from
hanging.
=> 🐛 explicitly remove MondooAuditConfig during teardown

api/v1alpha1/mondooauditconfig_types.go, config/crd/bases/k8s.mondoo.com_mondooauditconfigs.yaml, controllers/webhooks.go
This just involves annotating the Service fronting the webhook and
annotating the ValidatingWebhookConfiguration to inject the CA data.
=> ⭐️ add support for OpenShift TLS certificate injection

controllers/utils.go
We moved the primary container image for Mondoo Client from `mondoolabs/mondoo` to `mondoo/client`. This change uses the new image in the operator.
=> 🧹 switch to the new mondoo client image

.github/workflows/e2e-olm.yaml, .github/workflows/publish.yaml, .github/workflows/release-helm-chart.yaml, .github/workflows/release-manifests.yaml, charts/mondoo-operator/Chart.yaml, charts/mondoo-operator/templates/nodes-rbac.yaml, charts/mondoo-operator/values.yaml, config/manager/kustomization.yaml, controllers/webhook-manifests.yaml, release.sh
- reorganise GitHub workflows
- include `release.sh` to simplify updating all the files
- helm chart job runs after the container image build
- elm-olm test runs after the bundle build but is externalised to its own workflow file
It does not fully include the updating of the web hook manifest which is a followup task
=> ⭐️simplify release process

.github/workflows/e2e-olm.yaml, .github/workflows/publish.yaml
since the olm workflow is external now, the dependency needs to be defined in the main workflow
=> 🧹 move github actions needs to main workflow

Dockerfile, Makefile, controllers/webhooks.go
Take the $VERSION varaible and use it to set the Version variable in controllers/webhooks.go.
This will be used to store the version/tag of the mondoo-operator so that the Deployment/Pod for the webhook is in sync with the mondoo-operator version/tag by default.
You can of course override this by setting MondooAuditConfig.Spec.Webhooks.Image.Tag. And if you were to do a manual 'go build' without setting $VERSION, then it will default to just using the 'latest' tag.
=> set Version variable during build

README.md
For now let's just remove these links. Also spell out the complete
security e-mail address so it doesn't display oddly on GH.
=> Remove dead links to the docs page

api/v1alpha1/mondooauditconfig_types.go, config/crd/bases/k8s.mondoo.com_mondooauditconfigs.yaml
It was picking up unrelated comment lines, so seperate them such that only the lines we want are in the generated Description.
=> 🐛 clean up generated CRD Description

docs/user-manual-helm.md, docs/user-manual-kubectl.md
This PR fixes a couple of issues I ran into while following the docs...
```bash
kubectl apply -f mondoo-config.yaml
error: error validating "mondoo-config.yaml": error validating data: apiVersion not set; if you choose to ignore these errors, turn validation off with --validate=false
```
Missing `apiVersion: admissionregistration.k8s.io/v1`. 
```bash
kubectl get mondooauditconfigs
No resources found in default namespace.
```
Missing `-A`
```bash
kubectl get mondooauditconfigs -A
NAME            AGE
mondoo-client   20m
```
Signed-off-by: Scott Ford <scott@scottford.io>
=> 🧹 fixes doc config and command references

config/manifests/bases/mondoo-operator.clusterserviceversion.yaml
Recent work on the mondoo-operator means we can start claiming 'Seamless Upgrades' as a capability.
=> 🧹 move OLM capability to 'Seamless Upgrades'

.github/workflows/e2e-olm.yaml
The attempt to install mondoo-operator with operator-sdk using the bundle fails because the namespace mondoo-operator doesn't exists.
Move the creation of mondoo-operator Namespace to before the 'operator-sdk run bundle' command.
=> 🐛 create namespace before installing operator bundle

Makefile
It appears that act doesn't set up enough of a fake environment which
can cause some github action workflows that work on the real github to
fail when run through act.
Create some fake event data so that the checks against specific comments
in the spell-check workflow can succeed when run locally.
=> 🐛 fake some event data when running via act

Makefile, docs/development.md
The `make run` command was missing the new namespace. This change adds the default namespace so that the out-of-the-box setup is ready for development. In addition it updates the docs to ensure that all the required manifests are going to be deployed beforehand.
=> 🧹 update development docs and makefile

.github/workflows/e2e-olm.yaml
Seeing timeout messages during e2e of the type:
time="2022-03-30T18:37:24Z" level=fatal msg="Failed to run bundle:
install plan is not available for the subscription
mondoo-operator-v0-2-1-sub: timed out waiting for the condition\n"
The default is 2m0s, so increase to 5m.
=> increase olm timeout

RELEASE.md, release.sh
And update docs to reflect new 'release.sh' behavior of taking first
parameter as previous version and second parameters as new version.
The 'replaces' field in the ClusterServiceVersion should reference the
name of the previous ClusterServiceVersion object (ie the .metadata.name
field).
See some examples:
https://github.com/k8s-operatorhub/community-operators/blob/081ab9a4e33e4a4ff4472275d16ada512a7e6510/operators/couchbase-enterprise/2.1.0/manifests/couchbase-v2.1.0.clusterserviceversion.yaml#L1127
https://github.com/k8s-operatorhub/community-operators/blob/081ab9a4e33e4a4ff4472275d16ada512a7e6510/operators/prometheus/0.47.0/prometheusoperator.0.47.0.clusterserviceversion.yaml#L491
https://github.com/k8s-operatorhub/community-operators/blob/081ab9a4e33e4a4ff4472275d16ada512a7e6510/operat …
=> 🧹 change format for the 'replaces' field in OLM bundle

controllers/suite_test.go, controllers/utils.go, controllers/webhooks_test.go
=> 🧹 Allowed mocking the function for retrieving the container image from a remote registry

.github/workflows/test-report.yaml, .github/workflows/unit.yaml, .gitignore, Makefile
The extra workflow is needed in order to be able to support PRs from forked repos. This is explained [here](https://github.com/marketplace/actions/test-reporter#recommended-setup-for-public-repositories).
=>  ⭐ Added test reporting for units tests Github workflow

.github/workflows/e2e.yaml
Just like in the regular mondoo-namespace test, wait for the Pods. Otherwise we risk racing past to the next part of e2e and failing because we didn't wait.
More importantly, we've seen Pods fail to come up due to lack of resources in the minikube environment. So clean up the MondooAuditConfig from the mondoo-operator namespace test to free up some resource for the not-mondoo-operator tests.
=> 🧹 cleanup and wait for the Pods to come up

controllers/resources_requirements.go, controllers/resources_requirements_test.go
As CPU is a very compressible resource, we can ask for far less than 375m (which is really basically saying we need 1/3 of a full CPU). Bring that way back to 50m (5% of a CPU). Still allowing the Pod access to a full 1/2 a CPU in the event that a particular scan was CPU intensive.
For Memory, scale it back a bit from requesting 750M (which was 75% of the Pod Memory limit), down to 500M (50% of the limit). This should guarantee a minimum of .5GB with a bit of "overscheduling" the underlying cluster memory-wise).
closes #256 
=> 🧹 scale back the resource requests for Pods

api/v1alpha1/constants.go, api/v1alpha1/mondooauditconfig_types.go, config/crd/bases/k8s.mondoo.com_mondooauditconfigs.yaml, config/manager/manager.yaml, config/samples/k8s_v1alpha1_mondooauditconfig.yaml, config/samples/k8s_v1alpha1_mondoooperatorconfig.yaml, controllers/nodes.go, controllers/webhooks.go, controllers/webhooks_test.go, controllers/workloads.go, pkg/webhooks/core/webhook.go, pkg/webhooks/core/webhooks_test.go, pkg/webhooks/main.go, pkg/webhooks/utils/modes.go
Not specific to #246, but still worth fixing:
closes #246
=> ⭐️ webhook mode of permissive/enforcing

.github/workflows/release-helm-chart.yaml
Saw some e2e timeouts that were not reproducable locally. Raise timeout from 400s to 600s
=> 🧹 increase timeout during helm e2e

controllers/resources_requirements_test.go
Recently updated the resource requests/limits (in #258 ). Test case had old comment about what the percentages were. Make comments in test reflect reality.
Hat tip @tas50 
=> 🧹 make resource comments reflect reality

.github/workflows/release-helm-chart.yaml
Just like we manually add the MondooAuditConfig, add a step to remove it before doing 'helm uninstall'.
Otherwise, the MondooAuditConfig resource doesn't get cleaned up because the finalizer sticks around, and because it doesn't get removed, then the node/workload scanning resources also stick around.
=> 🧹 manually remove MondooAuditConfig for helm e2e

.github/workflows/lint.yaml, .github/workflows/spell-check.yaml, Makefile, controllers/nodes.go, controllers/nodes_test.go, controllers/service_monitor.go, controllers/suite_test.go, controllers/workloads.go, controllers/workloads_test.go, pkg/webhooks/core/webhooks_test.go, tests/integration/mondoo_installation_test.go, tests/integration/test_cluster.go
I noticed there is no linting step for the code base (only a spell checker). This PR adds [golangci-lint](https://golangci-lint.run/) action to the repo and extends the `Makefile` with a lint target
=> :star: Add linting step

controllers/nodes.go, controllers/nodes_test.go, controllers/workloads.go, controllers/workloads_test.go, tests/integration/mondoo_installation_test.go
Add the postfix '-node' to the DaemonSet so that the Pods can be more easily identified by name.
Add the postfix '-workload' to the Deployment (for workloads) so that the Pod can be more easily identified.
closes #242
=> 🧹 descriptive names for DaemonSet and Deployment

pkg/scanner/scanner.go, pkg/scanner/scanner_test.go, pkg/scanner/testdata/webhook-payload.json
add a simple http client for the mondoo scanner
=> ⭐️ add scanner client

config/webhook/manifests.yaml, controllers/webhook-manifests.yaml, controllers/webhooks.go, pkg/webhooks/handler/webhook.go, pkg/webhooks/handler/webhook_test.go, pkg/webhooks/main.go
Additionally, implement a custom deepEquals() for knowing when an existing webhook needs updating.
On update of an existing webhook, be sure to clear out any previous annotations to cover the case where a runtime change was made to handing TLS certs for the webhook.
closes #249
=> :star: extend webhook watching to Deployments

controllers/webhooks.go, tests/framework/installer/installer.go, tests/framework/utils/certificate_utils.go, tests/integration/mondoo_installation_test.go
Add some steps to test out the webhook functionality.
Manually create the certificates/Secret.
Enable the webhook.
Convert the webhook to a FailurePolicy of Fail (so that we can show the webhook is active and failing because we haven't completed the certificate configuration).
Attempt to modify a Deployment and expect it to fail (b/c Cert config not complete).
Add the CA data to the webhook.
Attempt to modify a Deployment and expect it to succeed.
closes #287 
=> ⭐ e2e for webhook

docs/user-manual-olm.md
This PR updates the OLM install docs. Fixes a references from the install via `kubectl` docs. Also updates OLM install references to point to OLM docs instead of `curl` command because the `curl` reference points to a specific version of OLM which will likely cause problems down the line. 
Signed-off-by: Scott Ford <scott@scottford.io>
=> 🧹 Updates OLM docs

pkg/scanner/scanner.go, pkg/scanner/scanner_test.go
The healthcheck is allowed to be unauthenticated, so set the Bearer header only if a token was provided.
A failed RunKubernetesManifests call can result in nil fields in the result.WorstScore. Protect access into that structure around a nil assertion.
=> 🧹 resist the urge to panic

controllers/nodes.go
Closes #288 
I tested it manually to verify these changes are sufficient to fix the issue. It seems to be working!
=> 🐛 Allow node scanning on rancher-provisioned controlplane and etcd nodes

README.md
The CI badge in the readme is broken on `main`. That happened when migrating the tests to the new framework. I just noticed it so therefor this PR.
=> 🐛 Fixed broken CI badge in readme

.github/workflows/publish.yaml
Similar to how the Makefile sets the 'build-arg', set it during the docker buildx github workflow.
=> set the docker build-arg during publish

.github/workflows/e2e-olm.yaml
Since the mondoo-operator Deployment pod isn't coming up, we aren't getting useful pod logs.
Try gathering logs from all Pods in the mondoo-operator namespace if something failed.
=> e2e-olm: gather logs from all pods generically

controllers/integration/integration_controller.go, controllers/integration/integration_controller_test.go, controllers/mondooauditconfig_controller.go, controllers/mondooauditconfig_controller_test.go
When trading a token for a Mondoo service account, don't wait for the periodic integration controller to run and perform the first CheckIn(). Just make an attempt right after saving the Secret with the Mondoo service account.
Update test cases to expect the additional CheckIn() API call, and restructure the Integration controller to more easily allow perfoming a CheckIn() using only the Integration MRN and the Mondoo service account data.
Addresses #343 
=> attempt an immediate CheckIn() after Register()

api/v1alpha2/mondooauditconfig_types.go, controllers/integration/integration_controller.go, controllers/integration/integration_controller_test.go
Condition will only appear if it was Degraded once. After clearing up, the condition will exist in the list, but be set to Status == false (with a "all is well" message).
=> set a condition if issues during integration CheckIn()

controllers/scanapi/resources.go
Required to make sure the scan API knows that it is running as a Kubernetes integration. The whole thing will start working only after a release of the Mondoo client with some changes from @vjeffrey 
=> 🐛 Set KUBERNETES_ADMISSION_CONTROLLER for scan API deployment

Makefile, pkg/utils/genericobjectdecoder/customobject.go, pkg/webhooks/handler/webhook.go
The controller-gen tool was seeing our 'customObjectMeta` struct and processing it into this empty config/crd/bases/_.yaml file
Update the 'make manifests' target to only process ./api and ./pkg/webhooks. Move the 'customObjectMeta' struct out of that path.
Closes #311 
=> 🐛 stop generating empty _.yaml file

controllers/admission/deployment_handler.go, controllers/admission/deployment_handler_test.go, controllers/admission/resources.go, pkg/webhooks/handler/webhook.go, pkg/webhooks/handler/webhook_test.go, pkg/webhooks/main.go
To follow allong with other integrations, set the 'mondoo.com/integration-mrn' label for scanned resources.
Update the webhook to accept this optional parameter, and set the label if the integration MRN was provided.
Update test cases.
Closes #354 
=> 🧹 set integration label when console integration is enabled

pkg/mondooclient/scanner_test.go
It is required for associating CI/CD assets. Update our test so that it can be used against a live Mondoo API.
=> 🧹 recent Mondoo API requires the cluster-id label

.github/workflows/publish.yaml, .github/workflows/tests.yaml, README.md
Specified a matrix strategy for the integration tests such that they are being ran against all currently supported k8s versions.
I intentionally did not add v1.21 as it is going to be in maintenance mode for another month and will be then dropped. I know that the tests will fail as the `CronJob` API there is not supported by our operator. That should be fine as in a month it is EOL. See [here](https://endoflife.date/kubernetes).
=> ⭐ Define a matrix for testing all currently supported k8s versions

api/v1alpha2/mondooauditconfig_types.go, controllers/admission/deployment_handler_test.go, controllers/scanapi/conditions.go, controllers/scanapi/deployment_handler.go, controllers/scanapi/deployment_handler_test.go, tests/integration/audit_config_base_suite.go, tests/integration/audit_config_namespace_test.go
In case the Service Account needed by the ScanAPI is missing, a condition will be added to the MondooAuditConfig.
This might be the case, when a MondooAuditConfig is created in a custom namespace.
We only create ServiceAccounts in the mondoo-operator namespace.
Fixes https://github.com/mondoohq/mondoo-operator/issues/382
=> 🧹 Include missing ServiceAccount in MondooAuditConfig conditions

pkg/utils/k8s/equality.go, pkg/utils/k8s/equality_test.go
I noticed that the operator doesn't compare the resource requests/limits for Deployments and CronJobs, so they never get updated. This PR fixes the issue
=> 🐛 Make sure Deployments and CronJobs are updated when resource requests/limits change

docs/deployment-configurations.md
This config couldn't be applied with `Kind`.
Fixes #389
=> 🐛 Fix typo in `MondooOperatorConfig`

.github/workflows/validate-actions.yaml, Makefile, api/v1alpha2/mondooauditconfig_types.go, cmd/mondoo-operator/operator/cmd.go, config/crd/bases/k8s.mondoo.com_mondooauditconfigs.yaml, controllers/mondooauditconfig_controller.go, controllers/mondooauditconfig_controller_test.go, pkg/health/health.go, pkg/health/health_test.go, tests/framework/utils/k8s_helper.go, tests/integration/audit_config_base_suite.go, tests/integration/audit_config_test.go
This adds the version of the operator which reconciled the `MondooAuditConfig`
to the `Status` section of the CR.
The new readiness check waits for all `MondooAuditConfigs` to include this version before the operator is considered ready.
Fixes #380
=> 🧹 Add operator version to status of `MondooAuditConfig`

Makefile, tests/framework/installer/installer.go, tests/framework/utils/k8s_helper.go
- Revert kustomization.yaml to previous state after applying them
The files contained the image tag with the current git hash
- Suppress stack traces during log collection
Sometimes there are no logs to collect
=> 🧹 Refactor parts of integration tests

.github/workflows/release-manifests.yaml
This will automatically generate the release notes, looking quite
the same as we currently doing it manually.
Support added here:
https://github.com/softprops/action-gh-release/releases/tag/v0.1.14
=> 🧹 Automatically generate release notes

config/manager/manager.yaml, controllers/admission/resources.go, controllers/k8s_scan/resources.go, controllers/nodes/resources.go, controllers/scanapi/resources.go
Only the scan-api Pod requiers a scratch dir for `/tmp`.
Now all our containers pass the related policy rule.
Fixes #422
=> ⭐ Run all containers with `readOnlyRootFilesystem` set to `true`

Makefile
Workaround for https://github.com/operator-framework/operator-registry/issues/984
Fixes #429
=> 🐛 Pin opm image to prevent `permission denied` errors

api/v1alpha2/mondooauditconfig_types.go, cmd/mondoo-operator/k8s_scan/cmd.go, config/crd/bases/k8s.mondoo.com_mondooauditconfigs.yaml, controllers/k8s_scan/container_image/conditions.go, controllers/k8s_scan/container_image/deployment_handler.go, controllers/k8s_scan/container_image/deployment_handler_test.go, controllers/k8s_scan/container_image/resources.go, controllers/k8s_scan/deployment_handler.go, controllers/k8s_scan/resources.go, pkg/inventory/inventory.go, pkg/mondooclient/client.go, pkg/mondooclient/client_test.go, pkg/mondooclient/mock/client_generated.go, tests/integration/audit_config_base_suite.go, tests/integration/audit_config_namespace_test.go, tests/integration/audit_config_test.go
Allow scanning container images that are used by the workloads in the cluster. Currently, this is implemented as a new `CronJob` that runs once per day because for large clusters container scanning can take a while.
=> ⭐ Container image scanning

controllers/admission/resources.go, controllers/scanapi/resources.go
`RequiredDuringSchedulingIgnoredDuringExecution` leads to problems on small clusters.
Fixes #442
=> 🐛 Change `PodAntiAffinity` to prevent scheduling errors

controllers/k8s_scan/resources.go, controllers/nodes/resources.go, controllers/scanapi/resources.go, pkg/utils/mondoo/container_image_resolver.go
Also set `runAsNonRoot` in the `securityContext` where missing.
relates-to #423
=> ⭐ Switch to mondoo client rootless images

controllers/mondooauditconfig_controller.go, controllers/status/operator_status.go, pkg/utils/mondoo/token_exchange.go, pkg/utils/tokenexchange/tokenexchange.go
Was starting work on the remote/managed MondooAuditConfig pieces, but will need to switch to a different task. Save the work up until now to extract the token exchange codepaths because the remote/managed MondooAuditConfig controller will need to make use of this functionality.
Also, bugfix around some potential nil conditions that are returned.
=> Extract token exchange

config/manager/manager.yaml, controllers/admission/resources.go
I noticed on my cluster that we are actually under-provisioning the operator and webhook. 
=> 🧹 Revised resources requests for operator and webhook

controllers/k8s_scan/resources.go, controllers/nodes/resources.go, controllers/nodes/resources_test.go, pkg/utils/k8s/resources_requirements.go
Having a 400m CPU request for the Node scanning Jobs is excessive for an hourly node scan where the completion time is not time sensitive.
Rather than have the Node resource defaults be shared with the singleton ScanAPI Deployment, allow for the Node default resource requirements to be different. Lower the CPU requests for the Node Jobs down to 50m so that scheduling a node scan doesn't request such a high amount of CPU on each node.
=> create separate default Node resource requirements

cmd/mondoo-operator/operator/cmd.go, controllers/mondooauditconfig_controller.go, controllers/scanapi/deployment_handler.go, controllers/scanapi/deployment_handler_test.go, controllers/scanapi/resources.go, pkg/utils/k8s/equality.go, pkg/utils/k8s/openshift.go, pkg/utils/mondoo/container_image_resolver.go, pkg/utils/mondoo/container_image_resolver_test.go
OpenShift will assign a range of allowed UIDs for Pods in each Namespace
to use. The static use of UID 101 for the ScanAPI Pod interferes with
that.
Additionally, use the UBI container image when running on OpenShift
=> 🐛 detect when running on OpenShift

controllers/nodes/resources.go
Since the `machine-id` is not a reliable identifier and the hostname cannot always be determined (e.g. in GKE #348), we move to the Kubernetes node name.
Closes #463 
=> 🐛 Use the node name as platformid for node scanning

config/samples/k8s_v1alpha2_mondooauditconfig_minimal.yaml, controllers/k8s_scan/container_image/resources.go, controllers/k8s_scan/resources.go, pkg/mondooclient/client.go
Request only the errors instead of the entire report collection (which we anyways discard). This allows us to lower the limits for the scan `CronJobs`
=> 🧹 Optimize kubernetes resources scan CronJobs

controllers/k8s_scan/container_image/resources.go, controllers/k8s_scan/resources.go, pkg/feature_flags/feature_flags.go, pkg/mondooclient/client.go
Allow enabling pod discovery by setting `FEATURE_DISCOVER_PODS` env var. If you'd like to test this you need to do the following:
1. Make sure minikube is running `minikube start`
2. In the `mondoo-operator` root directory run the following:
```bash
make generate-manifests
make load-minikube
kubectl apply -f mondoo-operator-manifests.yaml
``` 
3. Edit the mondoo-operator deployment to add the env var
```bash
kubectl edit -n mondoo-operator deployment mondoo-operator-controller-manager
```
It should look like this:
```yaml
....
containers:
- args:
- operator
- --health-probe-bind-address=:8081
- --metrics-bind-address=:8080
- --leader-elect
command:
- /mondoo-operator
env: # <-- this is the important bit
- name: FEATURE_DISCOVER_PODS
value: "1"
....
```
4. Apply the following …
=> ⭐ Allow enabling pod discovery with an env var

.github/workflows/edge-integration-tests.yaml, .github/workflows/integration-tests.yaml, .github/workflows/tests.yaml, tests/framework/utils/audit_config.go
=> ⭐ Create edge integration tests workflow

cmd/mondoo-operator/k8s_scan/cmd.go, controllers/k8s_scan/container_image/resources.go, controllers/k8s_scan/resources.go
Adds a timeout parameter for the scan `CronJobs`. The goal is to make sure that we don't keep stacking running scan `CronJobs`. Over the weekend I ran into the issue that the Mondoo client seems to get stuck occasionally during a scan or it gets killed due to OOM. If this happens the pending scan `CronJobs` remain pending forever and new ones are being added on top. This eventually eats all the cluster resources and the follow-up jobs are just queued to be scheduled.
This PR does NOT fix the Mondoo client issue but it does make sure that the operator properly handles such edge cases and does not eat up the cluster resources.
=> ⭐ Add timeout parameter for scan cronjobs

cmd/mondoo-operator/k8s_scan/cmd.go, cmd/mondoo-operator/operator/cmd.go, cmd/mondoo-operator/webhook/cmd.go, controllers/integration/integration_controller.go, controllers/integration/integration_controller_test.go, pkg/utils/logger/logger.go
Unify logging format for the operator, cronjobs and admission controller. It looks like this now:
```
2022-08-01T10:08:09Z    INFO    webhook setting up manager
2022-08-01T10:08:09Z    INFO    controller-runtime.metrics      Metrics server is starting to listen    {"addr": ":8080"}
2022-08-01T10:08:09Z    INFO    webhook setting up webhook server       {"version": "sha256-1cfc847f62242675f857d25a6c8e5c38488dfe07.sig"}
2022-08-01T10:08:09Z    INFO    webhook registering webhooks to the webhook server
2022-08-01T10:08:09Z    INFO    controller-runtime.webhook      Registering webhook     {"path": "/validate-k8s-mondoo-com"}
2022-08-01T10:08:09Z    INFO    webhook starting manager
2022-08-01T10:08:09Z    INFO    controller-runtime.webhook.webhooks     Starting webhook server …
```
=> 🧹 Unified logging style for operator, cronjobs and admission controller

.github/workflows/integration-tests.yaml, Makefile, README.md, tests/integration/audit_config_base_suite.go
I added k3d to the pipeline. k3d is the minikube equivalent for spinning up a k3s cluster (btw it is blazingly fast compared to minikube).
I also fixed a flaky integration test for the admission controller that was causing issues
=> ⭐ Add k3s to integration tests

controllers/nodes/resources.go
This fixes the issue of the crashing node scanning cronjobs for GKE
=> 🐛  Set connection platformId for node scanning

config/manager/manager.yaml
As discussed we want to enabled workload discovery by default but we still want to leave a "way out of it" if necessary. To do that we just use the feature flag but make sure we set it by default.
=> ⭐️ Enable workload discovery by default

cmd/mondoo-operator/operator/cmd.go, pkg/utils/k8s/api.go
Rather than fail later while the operator is up and running, just check
whether some of the resources we depend on to operator properly exist
in the cluster.
For the first pass, just check that Jobs exist (to prove that our
checks actually work) and whether CronJobs exist (to catch the case of
an EKS cluster running k8s 1.20 which lacks CronJobs v1 (but happens to
have CronJobs v1beta1)).
=> 🧹 check for required APIs at startup

.github/workflows/integration-tests.yaml, .github/workflows/publish.yaml
Instead of cancelling all test when 1 fails, let them run.
=> 🐛 Do not fail fast for matrix tests

.github/dependabot.yml
this dependency is updated as part of updating OperatorSDK versions.
=> 🧹 dependabot ignore k8s.io/api

.github/workflows/publish.yaml
The version that was being used for building the binary contained the architecture suffix, which causes the integration tests to break. This should fix the issue
=> 🧹 Use version without suffix when building operator binaries

Makefile
Test duration is getting closer, especially on EKS
=> 🧹 Increate timeouts for integration tests

PROJECT, config/crd/patches/cainjection_in_mondooauditconfigs.yaml, config/crd/patches/cainjection_in_mondoooperatorconfigs.yaml, config/default/kustomization.yaml, config/manifests/kustomization.yaml
Went through the OperatorSDK tutorial twice. Once with the traditional/default v3 and once with --plugins="go/v4-alpha" as suggested in https://github.com/kubernetes-sigs/controller-runtime/issues/1657#issuecomment-1236901482 .
Did a recursive diff between the two directories, and these were the differences.
We already have pretty much moved to v4 thanks to the changes in https://github.com/mondoohq/mondoo-operator/pull/411 , but this PR just attempts to apply some of the additional changes that would be made to the files if we had initialized the repo with "--plugins="go/v4-alpha" originally.
=> 🧹 apply changes from using v4 kubebuilder

go.mod, go.sum
go get github.com/google/go-cmp
go mod tidy
=> update go-cmp to 0.5.9

controllers/admission/resources.go, pkg/mondooclient/client.go, pkg/webhooks/handler/webhook.go
Enabled workload discovery for the admission controller. This depends on a Mondoo back-end and CLI release before we can fully test it and merge it. Ideally, we merge this and create an operator release once the Mondoo client has been released.
=> ⭐️ Enable workload discovery for admission controller

.github/env
The release failed because the operator SDK version was never updated for the github env.
=> 🐛 Update operator SDK version for CI

cmd/mondoo-operator/operator/cmd.go, controllers/resource_monitor/debouncer/debouncer.go, controllers/resource_monitor/debouncer/debouncer_test.go, controllers/resource_monitor/debouncer/mock/debouncer_generated.go, controllers/resource_monitor/register.go, controllers/resource_monitor/resource_monitor_controller.go, controllers/resource_monitor/resource_monitor_controller_test.go
For large clusters it is inconvenient to scan all cluster resources on each operator startup. This PR makes sure the initially observed resources are dumped instead of scanned
=> 🧹 Skip initial scan of cluster resources

go.mod, go.sum
CVE-2022-1996: github.com/emicklei/go-restful
CVE-2022-27191 golang.org/x/crypto
CVE-2022-27664 golang.org/x/net
GHSA-r48q-9g5r-8q2h github.com/emicklei/go-restful GHSA-8c26-wmh5-6g9v golang.org/x/crypto
=> Update deps to resolve identified CVEs

pkg/webhooks/handler/webhook.go, tests/integration/audit_config_base_suite.go
We added controls to flag individual pods that are not part of another deployment so our integration tests are now failing. We also need to fix:
- Pods should not run with NET_RAW capability
- Pods should not run with SYS_ADMIN capability
They shouldn't flag pods that don't explicitly disable these.
=> 🧹 Use deployments instead of pods for integration tests

config/manager/manager.yaml
If you want to disable it unset
FEATURE_ENABLE_GARBAGE_COLLECTION in the operator Deployment.
=> turn on garbage collection by default

controllers/k8s_scan/deployment_handler_test.go, pkg/utils/k8s/cron_job.go
I noticed that we are reporting an error status for each of the scans whenever the scan is actually active. This PR fixes the bug and adds a test for that case.
=> 🐛 Do not report error status during an active scan

.github/workflows/integration-tests.yaml, .github/workflows/security-tests.yaml, .github/workflows/tests.yaml
This fixes the error message:
'Unexpected input(s) 'github-token', valid inputs are ['repository', 'ref', 'token', 'ssh-key', 'ssh-known-hosts', 'ssh-strict', 'persist-credentials', 'path', 'clean', 'fetch-depth', 'lfs', 'submodules', 'set-safe-directory']
=> 🐛 Fix token for checkout

.github/workflows/security-tests.yaml
Name has changed: https://github.com/mondoohq/actions/releases/tag/v0.7.0
Fixes #591
=> 🐛 Fix updated terraform action

.github/workflows/integration-tests.yaml, .github/workflows/security-tests.yaml, .github/workflows/tests.yaml, .github/workflows/unit-tests.yaml
This will bring back the integration and security tests into the PR.
It will also allow us dependabot and fork PRs. But we need to apply a label, before the tests start.
The label is also directly removed after the workflow starts, to prevent later commits from just starting the tests again.
=> 🧹 Re-work PR workflows

.github/workflows/cloud-tests.yaml, .github/workflows/integration-tests.yaml, .github/workflows/lint.yaml, .github/workflows/publish.yaml, .github/workflows/release-manifests.yaml, .github/workflows/unit-tests.yaml
Also use setup-go internal cache instead of separate action.
Fixes #597
=> 🧹 Update actions to use Node 16

.github/workflows/tests-forks.yaml, .github/workflows/tests.yaml
This prevents duplicate workflow runs for non-forks/dependabot PRs
=> 🐛 Use separate entrypoints to workflows

api/v1alpha2/mondooauditconfig_types.go, config/crd/bases/k8s.mondoo.com_mondooauditconfigs.yaml, config/rbac/kustomization.yaml, config/rbac/webhook_service_account.yaml, controllers/admission/resources.go, tests/integration/audit_config_namespace_test.go
it is considered bad form to use the 'default' ServiceAccount in any Namespace. give the webhook its own ServiceAccount (with no special permissions associated with it), and use that webhook.
Extend the MondooAuditConfig for the case where a MondooAuditConfig is installed somewhere besides 'mondoo-operator' so that a user can provide/specify their own SerivceAccount in whatever Namespace the MondooAuditConfig was installed onto.
=> 🧹 webhook shouldn't use default serviceaccount

.github/workflows/test-report.yaml
The test reporting is currently broken for our integration tests. This PR fixes that
=> 🐛 Fix integration test reporting

controllers/resource_monitor/debouncer/debouncer.go, controllers/resource_monitor/debouncer/debouncer_test.go, controllers/resource_monitor/debouncer/mock/debouncer_generated.go, controllers/resource_monitor/register.go, controllers/resource_monitor/resource_monitor_controller.go, controllers/resource_monitor/resource_monitor_controller_test.go, pkg/mondooclient/client.go, pkg/mondooclient/mock/client_generated.go
There are certain resources that are not getting garbage collected correctly. I believe it's because they are missing the `managedBy` field. I cannot confirm 100% that this is the root cause for the issue, since I cannot check it in the database but this is a bug anyhow.
=> 🐛 Set managedBy when scanning resources via the resource monitor

.github/workflows/cloud-tests.yaml
The problem was that we do not map 1:1 each container tag to an operator version. For example, if we pull the container image with a tag `main` the operator version inside is not `main`. With this change before the test suite is started we retrieve the operator version from inside the container. In this way it should be always the correct one
=> 🧹 Retrieve real operator version before cloud tests start

.github/workflows/tests-forks.yaml
When we apply the label, the actor is changed to our user. Same for the previous login field. That prevented the checks from starting. Only a `@dependabot rebase` or `@dependabot recreate` triggered the checks again.
This field holds the dependabot user, even when we apply a label.
=> 🐛 Check for user login

controllers/scanapi/deployment_handler.go
This changed, now that we try to find the secrets automatically.
Fixes #624
=> 🐛 Fix message about private image scanning

pkg/mondooclient/client.go
We received an issue that namespace filtering does not work as expected. After debugging it I discovered it actually never worked because the wrong options were set in the inventory. This PR fixes the issue
=> 🐛 Fix namespace filtering

.github/workflows/publish-images.yaml, .github/workflows/publish.yaml
Our workflows currently fail when publish is triggered by a dependabot PR. Again becasue of missing access to secrets.
This debug output should provide the data to decide on how to progress.
=> 🧹 Add debugging output to publish workflow

tests/integration/audit_config_base_suite.go
`cmd` cannot be reused:
https://pkg.go.dev/os/exec#Cmd
Fixes #658
=> 🐛 Fix restart of port-forward

.github/workflows/tests-forks.yaml
This should fix: https://github.com/mondoohq/mondoo-operator/actions/runs/3458628601/jobs/5773237663
=> 🐛 Checkout before using GH CLI

pkg/utils/logger/logger.go
This setting will only show stack traces on panic.
Fixes #684
=> 🐛 Do not show stack traces on error

controllers/nodes/resources.go, controllers/scanapi/resources.go, pkg/feature_flags/feature_flags.go, pkg/utils/mondoo/container_image_resolver.go, tests/framework/installer/installer.go, tests/framework/installer/settings.go, tests/integration/audit_config_base_suite.go, tests/integration/audit_config_cnspec_test.go
Integrate cnspec into the operator. For now I added a feature flag that allows us to switch between mondoo and cnspec so we can easily test the cnspec integration without bothering other users:
=> ⭐️ Add cnspec feature flag

tests/framework/installer/settings.go, tests/framework/utils/audit_config.go, tests/integration/audit_config_cnspec_test.go, tests/integration/audit_config_namespace_test.go, tests/integration/audit_config_test.go, tests/integration/audit_config_upgrade_test.go
Since cnspec doesn't have edge releases at the moment, the edge tests are failing. This PR makes sure edge tag is not used for cnspec.
=> 🐛 Do not use edge tag for cnspec

.github/workflows/publish.yaml, Makefile, cmd/mondoo-operator/operator/cmd.go, cmd/mondoo-operator/version/cmd.go, cmd/mondoo-operator/webhook/cmd.go, pkg/version/version.go
The cloud tests were broken because the version set in the `mondoo-operator` binary was `nightly` but the released container image is `main`. Due to this mismatch a very old operator binary was used with the latest mondoo client which is incompatible.
I also added the commit sha to the binary to be able to exactly pinpoint which version we are running (because`main` doesn't say much).
=> 🐛 Fix nightly build and set operator commit in binary

.github/workflows/cloud-tests.yaml
Currently, we get no notification when the cloud tests fail. I added Discord notifications to make sure we keep an eye on this.
=> 🧹 Send Discord notification for failed cloud tests

.github/workflows/cloud-tests.yaml, cmd/mondoo-operator/version/cmd.go
The cloud tests are actually parsing the version output so it broke when I changed it. This PR makes sure the version can be printed in a way that the workflow can parse it
=> 🐛 Update printing of operator version

pkg/webhooks/handler/webhook.go
Lowers the memory usage for the admission controller by not requesting the full scan report from the scan API
=> 🐛 Use error report type for admission controller

.github/terraform/aks/variables.tf, .github/workflows/cloud-tests.yaml, README.md
AKS 1.22 is no longer supported:
https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions\?tabs\=azure-cli\#aks-kubernetes-release-calendar
=> 🧹 Remove AKS 1.22

.github/workflows/publish.yaml
This partially reverts https://github.com/mondoohq/mondoo-operator/pull/742
Permission are taken from these:
https://github.com/dorny/test-reporter/issues/149
https://github.com/mondoohq/cnquery/pull/105
https://github.com/helm/chart-releaser-action\#example-workflow
=> 🐛 Fix failing test reporter

pkg/mondooclient/client.go
Currently, all workloads are discovered when scanning container images. This works but makes the container image scan unnecessarily slower since we are scanning more assets than we are supposed to. This PR makes sure we discover only the container images when the container image scan job is running
=> 🧹 Discover only container images when scanning containers

config/manager/manager.yaml, pkg/feature_flags/feature_flags.go
It seems like helmify changed the way it sets env vars in the chart. It is now using a reference instead of directly setting the value in the template. Since we use "1" for feature flags, it is causing issues. When the value is loaded as a reference it doesn't understand it is a string and sets 1 as a number, which Kubernetes doesn't accept. It causes the following failure https://github.com/mondoohq/mondoo-operator/actions/runs/4407953231/jobs/7722399178
In this PR I made sure we can use "true" or "1" for the operator's feature flags. As a workaround for helmify, I set the variable to "true" instead of "1" which should work.
@joelddiaz I think we can also just remove the garbage collection feature flag completely. If you agree, let's do that. I still want to make a patch release with …
=> 🐛 do not use numbers for feature flags

.github/workflows/publish.yaml
The workflow is broken because of a new major version of cosign. This should fix it
=> 🐛 fix cosign in github workflows

cmd/mondoo-operator/operator/cmd.go, controllers/service_monitor.go, pkg/utils/k8s/api.go, pkg/utils/k8s/openshift.go
When testing with ROSA it seem like `config.openshift.io` isn't present there. I added another API that I saw available to the openshift check
=> 🧹 check for multiple apis when determining openshift

controllers/mondooauditconfig_controller.go, controllers/nodes/deployment_handler.go, controllers/nodes/deployment_handler_test.go, controllers/nodes/resources.go, controllers/nodes/resources_test.go
When scanning Openshift nodes that run RHCOS it is required to run the scan in a privileged container since otherwise we have no access to `/proc`
=> 🐛 run node scanning in privileged container for openshift

controllers/scanapi/resources.go
Just to make sure that we can properly garbage collect large spaces
=> 🧹 set http timeout for cnspec api to 30min

controllers/nodes/deployment_handler.go, controllers/nodes/deployment_handler_test.go, pkg/feature_flags/feature_flags.go, tests/integration/audit_config_base_suite.go
Removed the node garbage collect flag and it is now enabled by default
I also extended the unit tests and integration tests to check that the new cronjob is properly created.
=> 🧹 remove node garbage collect feature flag and extend tests

charts/mondoo-operator/values.yaml, config/manager/manager.yaml, pkg/utils/k8s/resources_requirements.go
We have seen several OOM issues. This PR increases the default requests and limits for the operator itself and for the node scanning jobs. I use these values on my cluster and it seems to be working fine with them. However, for larger cluster it is possible that the operator might need a more memory than what I have set here
=> 🧹 increase operator and node scanning requests and limits

.github/workflows/cleanup-mondoo-space.yaml
Only disable for now. Let's see how the new automatic cleanup works out. We can remove this completly in a couple of days.
=> 🧹 Disable cleanup workflow

Makefile
We cannot use `yq` because it cannot work with templates.
Fixes #751
=> 🐛 Fix duplicate labels for Helm chart

cmd/mondoo-operator/operator/cmd.go, controllers/metrics/metrics.go, controllers/metrics/metrics_test.go
#213 
Currently, this only adds one metrics `mondoo_audit_config` which shows the number of mondoAuditConfigs.
=> :sparkles: add custom metrics

.github/workflows/lint.yaml, Makefile
The errors polute the logs and make it hard to find real problems
For some background, see https://github.com/mondoohq/mondoo-operator/pull/812
=> 🐛 Fix tar errors during golangci-lint execution

.github/workflows/publish.yaml
Use the same versions as for our integration tests.
=> 🧹 Bump k8s versions for Helm and OLM

.github/workflows/cloud-tests.yaml, .github/workflows/integration-tests.yaml, .github/workflows/publish.yaml
Update minikube and k3s to the latest minor versions and managed k8s to the latest major.
=> 🧹 Bump k8s versions

.github/workflows/cloud-tests.yaml, .github/workflows/lint.yaml
This adds the GHA monitor to some of our workflows: https://github.com/GitHubSecurityLab/actions-permissions/tree/main/monitor 
These workflows do not have permissions specified. The action should tell us the least needed privileges.
=> 🧹 Monitor workflows for least privileges

Makefile, controllers/scanapi/deployment_handler.go, controllers/scanapi/deployment_handler_test.go
The node GC depends on the Scan API. Because of that we also need to create the Scan API when only node scanning is active.
Fixes https://github.com/mondoohq/server/issues/6267
=> 🐛 Enable Scan API also for node scanning

.github/workflows/cnspec.yaml
Can be triggered manually. As input we provide the version of cnspec to release and the action will build the following container flavours:
- normal
- rootless
- ubi
- ubi rootless
Run: https://github.com/mondoohq/mondoo-operator/actions/runs/6324829721
=> 🐛 cnspec v9 action

.github/workflows/cnspec.yaml
The cnspec releases always start with a leading `v`. The action that releases the pre-bundled cnspec with the required providers for the operator needs the version to have no leading `v`. After merging this we can add a step in the cnspec release flow to call this workflow and automatically build the container for every cnspec release
Successful run https://github.com/mondoohq/mondoo-operator/actions/runs/6402540882
=> 🧹 make sure cnspec release works with versions containing 'v'

.github/workflows/cnspec.yaml
This is needed in order to call the workflow from the cnspec repo
=> 🧹 add repository dispatch event for cnspec container build

pkg/utils/mondoo/container_image_resolver.go
we can now use the stable v9 cnspec image
=> 🧹 use stable v9 image for cnspec

.github/workflows/cnspec.yaml
Just noticed that the repo dispatch has a different flow for parsing the input
=> 🐛 parse repository dispatch payload for cnspec

.github/workflows/cnspec.yaml, cnspec.Dockerfile
currently, we always use the `root` image as base. This PR makes sure we always start with a `root` image, install the providers in the system directory and then we switch the user to `101` to make it rootless. We release only `X-rootless` and `X-ubi-rootless` images since those are the only ones that the operator uses
=> 🐛 release the correct cnspec container flavours

controllers/container_image/deployment_handler.go, controllers/container_image/deployment_handler_test.go
When the `MondooAuditConfig` defiens a custom image, also use it for the container scan `CronJob`.
Fixes #887
=> 🐛 Use defined scanner image also for container scan

tests/framework/installer/installer.go, tests/framework/nexus/client.go
Before this PR, we saw errors like:
'failed to parse response: http status 500: {"code":2,"message":"integration not found"}}'
That happened because of timing and re-use issues. This PR takes of this.
=> 🐛 Fix integration test with external installation

.github/workflows/cloud-tests.yaml
Otherwise we hit the VPC quota limit.
=> 🧹 Do not run too many tests in parallel

Makefile, tests/framework/installer/installer.go, tests/framework/nexus/assets/assets.go, tests/integration/audit_config_base_suite.go
This fixes the failing OLM tests where we have more workloads than for other tests. The default number of assets fetched from upstream is 25. That wasn't enough for OLM clusters.
=> 🐛 Fetch more assets from upstream

api/v1alpha2/mondooauditconfig_types.go, config/crd/bases/k8s.mondoo.com_mondooauditconfigs.yaml, controllers/container_image/deployment_handler.go, controllers/container_image/deployment_handler_test.go, controllers/container_image/resources.go, controllers/k8s_scan/deployment_handler.go, controllers/k8s_scan/deployment_handler_test.go, controllers/k8s_scan/resources.go, controllers/nodes/deployment_handler.go, controllers/nodes/deployment_handler_test.go, controllers/nodes/resources.go, docs/user-manual.md, go.mod, go.sum, pkg/utils/k8s/equality.go, pkg/utils/k8s/equality_test.go
It is now possible to change the CronJob schedule for the different types of CronJobs via the `MondooAuditConfig`.
Fixes #888
=> ✨ Expose CronJob schedule via config

tests/integration/audit_config_base_suite.go
The test worked accidentally with single node clusters, but failed with two node clusters, e.g., EKS.
=> 🐛 Fix test for number of gc CronJobs

.github/workflows/test-report.yaml
For each PR it is called at least twice:
- Run Test
- Run Test (forks & dependabot)
But one of them was skipped and does not have an artifact. That results in errors.
With the data from the debug step, we should be able to write a condition which prevents this.
=> 🧹 Debug report test

controllers/container_image/deployment_handler.go, controllers/container_image/deployment_handler_test.go, controllers/container_image/resources.go, controllers/k8s_scan/deployment_handler.go, controllers/k8s_scan/deployment_handler_test.go, controllers/k8s_scan/resources.go, controllers/nodes/deployment_handler.go, controllers/nodes/deployment_handler_test.go, controllers/nodes/resources.go, controllers/nodes/resources_test.go, pkg/utils/mondoo/condition.go, tests/framework/installer/installer.go, tests/framework/utils/k8s_helper.go, tests/integration/audit_config_base_suite.go
The CronJob schedule was changed with every reconcile. This PR adds the schedule during CronJob creation to the MondooAuditConfig so that it can later be re-used.
=> 🐛 Fix CronJob schedule

controllers/admission/conditions.go, controllers/admission/deployment_handler.go, controllers/container_image/conditions.go, controllers/container_image/deployment_handler.go, controllers/k8s_scan/conditions.go, controllers/k8s_scan/deployment_handler.go, controllers/nodes/conditions.go, controllers/nodes/deployment_handler.go, controllers/nodes/deployment_handler_test.go, controllers/scanapi/conditions.go, controllers/scanapi/deployment_handler.go, controllers/scanapi/deployment_handler_test.go, pkg/utils/mondoo/condition.go, tests/integration/audit_config_base_suite.go, tests/integration/audit_config_oom_test.go, tests/integration/audit_config_test.go
This adds e2e tests for OOM of Scan API and node scan. This covers the two different cases we currently have: Deployment and CronJob.
Fixes #940
=> 🧹 Add e2e OOM tests

docs/user-manual.md
In some cases, the uninstall of the operator may fail. This adds docs on how to clean up in these cases.
Fixes #910
=> 📄 Add docs on how to clean up failed uninstall

cmd/mondoo-operator/operator/cmd.go
Right now for new installations via the UI, the operator crashes because it cannot find the secret `mondoo-client` it only gets created when the registration token is exchanged for a service account. This means the operator can never start
=> 🐛 do not crash on failure to report state

controllers/container_image/deployment_handler.go, controllers/container_image/deployment_handler_test.go, controllers/container_image/resources.go, controllers/k8s_scan/deployment_handler.go, controllers/k8s_scan/deployment_handler_test.go, controllers/k8s_scan/resources.go, controllers/mondooauditconfig_controller.go, controllers/mondooauditconfig_controller_test.go, controllers/nodes/deployment_handler.go, controllers/nodes/deployment_handler_test.go, controllers/nodes/resources.go, go.mod, go.sum, pkg/utils/k8s/equality.go, tests/framework/utils/audit_config.go
2 issues here make the cronjobs be updated endlessly and never execute:
- the concurrency policy for cronjobs wasn't properly set in the update flow
- the crontab was never updated in the `MondooAuditConfig` when cronjobs just had to be updated. This meant that for existing installations of the operator, the cronjobs would never match what is in the `MondooAuditConfig`. The CRD would always have an empty `Schedule` and the cronjobs would always try to use the current time to create a schedule
=> 🐛 fix endless updates of cronjobs

docs/operator-upgrades.md
Restructure this around Helm, OLM, and manual installs and remove mention of pre-1.0 since we've already upgraded those folks at this point.
=> Rework upgrade docs to not mention pre-1.0

controllers/mondooauditconfig_controller.go, controllers/mondooauditconfig_controller_test.go
When the deprecated setting `kubernetesResources.containerImageScanning` is set to `true` the schedule for container scans isn't properly set. This PR makes sure when the deprecated setting is used, the new one is set too
Fixes #1005
=> 🐛 properly handle deprecated container scan setting

tests/framework/installer/installer.go, tests/framework/installer/settings.go, tests/framework/utils/k8s_helper.go, tests/integration/audit_config_namespace_test.go, tests/integration/audit_config_oom_test.go, tests/integration/audit_config_test.go, tests/integration/audit_config_upgrade_test.go
this doesn't change anything functionally but makes a more human-friendly structure of the test logs. We now store the logs for a suite in a separate folder. Inside there is a folder for each individual test:
=> 🧹 restructure test logs for e2e tests

controllers/admission/deployment_handler.go
I don't understand why we ever did that. It is causing issues in enforcing mode since we are deleting the only available webhook and then we brick the cluster because nothing can pass
We do the same type of update flow for the scan api, for example, with no issues
=> 🐛 fix admission update flow

config/webhook/manifests.yaml, controllers/admission/webhook-manifests.yaml
occasionally our integration tests fail because the scan api takes longer than 10s to respond to an admission call. Here we change the default 10s timeout to a longer one to make sure the tests succeed even on slower clusters
=> 🧹 extend the timeout for the validating webhook

config/webhook/kustomization.yaml, config/webhook/manifests.yaml, config/webhook/webhook_patch.yaml, controllers/admission/webhook-manifests.yaml
the files are auto-generate, so we have to add the timeout via a patch
=> 🧹 properly set the validating webhook timeout

controllers/nodes/deployment_handler.go
first update the node scan conditions and then configure node GC. This makes sure the node GC doesn't interfere with status reporting
=> 🧹 set node scan conditions before setting up node gc

tests/framework/nexus/assets/assets.go, tests/integration/audit_config_base_suite.go
Explicitly assert which policies have been scored for each asset. Useful to make sure we aren't scoring policies that shouldn't be scored for a specific asset type
=> 🧹 assert scored policies in e2e tests

controllers/container_image/resources.go, tests/integration/audit_config_base_suite.go
makes sure private container image scans work. The issue was that the container pull secrets were overriding the mondoo folder, so the mondoo config was no longer available. That resulted in failure to communicate with upstream
=> 🐛 fix private image container scans

api/v1alpha2/mondooauditconfig_types.go, config/crd/bases/k8s.mondoo.com_mondooauditconfigs.yaml, controllers/mondooauditconfig_controller.go, controllers/mondooauditconfig_controller_test.go, controllers/nodes/deployment_handler.go, controllers/nodes/deployment_handler_test.go, controllers/nodes/resources.go, controllers/nodes/resources_test.go, pkg/utils/k8s/create_update.go, tests/framework/utils/audit_config.go, tests/integration/audit_config_base_suite.go, tests/integration/audit_config_namespace_test.go, tests/integration/audit_config_oom_test.go, tests/integration/audit_config_test.go
Allow using deployments for node scans instead of cronjob. For fully utilized clusters, cronjobs may not be able to run. Even if we can schedule the job now, there is no guarantee the node will have resources 1h from now. Using deployments ensures that once the deployment is scheduled it will always run a node scan, because the resources are already reserved.
=> ⭐️ allow using deployments for node scans

pkg/utils/mondoo/container_image_resolver.go
if we run the operator outside of the cluster, it tries to fetch the operator deployment inside the cluster, which doesn't exist. In that case we cannot continue with the reconcile loop because we error out on the operator image resolution. It's annoying when debugging locally.
With this change if we cannot find the operator deployment in the cluster, we return the default operator image
=> 🧹 do not error out when running operator outside of the cluster

.github/actions/spelling/line_forbidden.patterns, .github/actions/spelling/patterns.txt, .github/workflows/cla.yaml, .github/workflows/link-check.yaml, README.md, config/manifests/patches/description.yaml, docs/development.md, docs/user-manual.md
These have been broken for a while
=> Fix dead docs links

controllers/nodes/resources.go, tests/integration/audit_config_base_suite.go
The node scanning deployments were constantly updating because we were overriding annotations.
=> 🐛 fix node scanning deployments update loop

Makefile, controllers/nodes/resources.go, controllers/nodes/resources_test.go, controllers/scanapi/resources.go, controllers/scanapi/resources_test.go, pkg/utils/gomemlimit/gomemlimit.go, pkg/utils/gomemlimit/gomemlimit_test.go
This should further help reduce OOMkills for the modified Pods.
This is the official doc for this: https://go.dev/doc/gc-guide#Suggested_uses
An example of another software using this: https://docs.dapr.io/operations/hosting/kubernetes/kubernetes-production#setting-soft-memory-limits-on-dapr-sidecar
=> ✨ Use GOMEMLIMIT for scanning Pods

tests/integration/audit_config_base_suite.go
we dropped the eol policy, so the tests should no longer expect it
=> 🧹 fix integration tests
